openapi: "3.0.0"

info:
  title: API classes
  version: "1.0"
  description: admin-api API

servers:
  - url: http://localhost:8080/admin-app/api

tags:
  - name: AppRoles
    description: AppRoles specific data.

paths:
  /appRoles:
    get:
      tags:
        - AppRoles
      summary: Get All AppRoles
      operationId: getAllAppRoles
      parameters:
        - name: currentPage
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: sizePage
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/classes/ClasseDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
  /classes-reference:
    get:
      tags:
        - Classes
      summary: Retrieve an classe
      operationId: getClasse
      parameters:
        - name: idClasse
          in: path
          required: true
          schema:
            type: integer
            format: int64
          example:
            idClasse: 1
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '../model/classes/ClasseDTO.yml'
              examples:
                client1:
                  value:
                    idClient: 1
                    nom: DIARYATOU

                client2:
                  value:
                    idClient: 1
                  nom: DIARYATOU


  /appRoles-reference:
    get:
      tags:
        - AppRoles
      summary: Retrieve an AppRole
      operationId: getAppRole
      parameters:
        - name: idAppRole
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                 $ref: '../model/classes/ClasseDTO.yml'

        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
