openapi: "3.0.0"

info:
  title: API classes
  version: "1.0"
  description: admin-api API

servers:
  - url: http://localhost:8080/admin-app/api

tags:
  - name: AppRoles
    description: AppRoles specific data.

    /classes/{idClasse}:
    $ref: '../components/api/classes.yml#/paths/~1classes-reference'
